# testcato_config.yaml


# default: agent1
#
# When using multiple agents, you can specify which agent to use for each task or mark the default agent using the above 'default' field.
#
# agent1:
#   type: openai
#   model: gpt-4
#   api_key: YOUR_OPENAI_API_KEY
#
# Add more agents below as agent2, agent3, etc.
# agent2:
#   type: azure
#   model: gpt-4
#   api_key: YOUR_AZURE_API_KEY


