# testcato_config.yaml


# default: gpt
#
# When using multiple agents, you can specify which agent to use for each task or mark the default agent using the above 'default' field.
#
# gpt:
#   type: openai
#   model: gpt-4.1-mini
#   api_key: <YOUR_OPENAI_API_KEY>
#   api_url: https://api.openai.com/v1/chat/completions

